
/*!
** @file   ObjDict.c
** @author CAN Festival -- NNP
** @date   OD File produced: 2011-03-06 21:48:07.869000
**
** @brief This file is generated by the NNP Tool -- Object Dictionary Editor, as 
** originally developed by CAN Festival and modified by the NNP Team. 
** Specific contents are detailed in Object Dictionary Template.
** Editor modification: 4/29/2010 -- rev 1.0.0 
**
** This ObjDict.c file is generated from PulseGenerator4ch.odnn
** 
*/  

/*This object dictionary file should only be modified by the Object Dictionary Editor */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS8 clockRate = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 Control_ScriptStatus = 0x0;		/* Mapped at index 0x2001, subindex 0x01 */
UNS8 Control_CurrentGroup = 0x0;
UNS8 Control_profileWrite = 0x0;
UNS8 Control_profileSelect = 0x0;
UNS8 X_Network[4] = {0x0, 0x0, 0x0, 0x0};		/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Temperature = 0x0;		/* Mapped at index 0x2003, subindex 0x00 */
UNS8 Status_modeSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x01 */
UNS8 Status_numTPDO = 1;
UNS8 Status_numRPDO = 1;
UNS8 Status_channelSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x02 */
UNS8 Status_profileSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x03 */
UNS8 Status_profileWrite = 0x0;		/* Mapped at index 0x2010, subindex 0x04 */
UNS8 Status_NodeId = 4;
UNS16 Status_TestValue = 0x00;
UNS16 Status_NodeTest = 0;
UNS8 Accelerometers[4] = 
{ 0x00,  0x00,  0x00, 0x00 };		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 AccelerometersFiltered[4] = 
{ 0x00,  0x00,  0x00, 0x00 };         /* Mapped at index 0x2011, subindex 0x01 */
INTEGER8 AccelerometersTilt[4] = 
{ 0x00,  0x00,  0x00, 0x00 };         /* Mapped at index 0x2011, subindex 0x01 */
UNS8 AccelerometerSettings = 0;  /*0x2012*/
UNS32 AddressRequest = 0x00000000;
UNS8 memorySelect = 0x00;
UNS8 triggerReadMemory = 0x00;
UNS8 writeByteMemory = 0x00;
UNS8 statusByteMemory = 0x00;
UNS8 ReadMemoryData[36] = 
{ 0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00,  0x00,  0x00,  0x00,\
  0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00,  0x00,  0x00,  0x00, \
  0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00 , 0x00,  0x00,  0x00 };
UNS16 addressCounter = 0x0000;
UNS16 CAN_FormErrors = 0x00;
UNS16 CAN_StuffErrors = 0x00;
UNS16 CAN_BitErrors = 0x00;
UNS16 CAN_OtherErrors = 0x00;
UNS16 CAN_TotalErrors = 0x00;
UNS16 CAN_Rx_ErrCounter = 0x00;
UNS16 CAN_Tx_ErrCounter = 0x00;
UNS16 CAN_Receive_BEI = 0x00;
UNS16 CAN_Receive_Messages = 0x00;
UNS16 CAN_Transmit_Messages = 0x00;
UNS16 CAN_Interrupts_Off = 0x00;
UNS8 DiagnosticsEnabled = 0x01;
UNS8 Diagnostic_VIN = 0x00;
UNS8 Diagnostic_VIC = 0x00;
UNS8 Diagnostic_VOS = 0x00;
UNS8 Diagnostic_3V3 = 0x00;
UNS8 CommandValues[8] =
{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
UNS8 Channel_Config_AmpMax[8] = 
{0x00, 0xC8, 0x00, 0xC8, 0x00, 0xC8, 0x00, 0xC8};		/* Mapped at index 0x3210, subindex 0x01 */
UNS16 Channel_Config_Period[4] = 
{0x0053, 0x0053, 0x0053, 0x0053};		      /* Mapped at index 0x3210, subindex 0x02 */
UNS16 Channel_StimVOS = 2040;   /* units in DAC bits ~ VOS*60, Mapped at index 0x3210, subindex 0x03  */
UNS16 Channel_MinVOS = 2040;   /* units in DAC bits ~ VOS*60, Mapped at index 0x3210, subindex 0x04  */
UNS8 Channel_InRegulation[4] = { 0x0, 0x0, 0x0, 0x0 };	
UNS8 X_ChannelMap[4] = { 0x0, 0x0, 0x0, 0x0 };		              /* Mapped at index 0x3211, subindex 0x00 */
UNS8 Chan1_SetValues[2] = { 0x00, 0x00 };  /* Mapped at index 0x3212, subindex 0x01 */
UNS8 Chan2_SetValues[2] = { 0x00, 0x00 };
UNS8 Chan3_SetValues[2] = { 0x00, 0x00 };
UNS8 Chan4_SetValues[2] = { 0x00, 0x00 };		
UNS8 Y_Current[8] = 
{ 0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 0x00 };		/* Mapped at index 0x3213, subindex 0x00 */
UNS8 FuncGroup_ChanPattern01 = 0;
UNS8 FuncGroup_ChanPattern02 = 0;
UNS8 FuncGroup_ChanPattern03 = 0;
UNS8 FuncGroup_ChanPattern04 = 0;
UNS8 FuncGroup_ChanPattern05 = 0;
UNS8 FuncGroup_ChanPattern06 = 0;
UNS8 FuncGroup_ChanPattern07 = 0;
UNS8 FuncGroup_ChanPattern08 = 0;
UNS8 FuncGroup_ChanPattern09 = 0;
UNS8 FuncGroup_ChanPattern10 = 0;
UNS8 FuncGroup_ChanPattern11 = 0;
UNS8 FuncGroup_ChanPattern12 = 0;
UNS8 FuncGroup_ChanPattern13 = 0;
UNS8 FuncGroup_ChanPattern14 = 0;
UNS8 FuncGroup_ChanPattern15 = 0;
UNS8 FuncGroup_ChanPattern16 = 0;
UNS8 FuncGroup_ChanPattern17 = 0;
UNS8 FuncGroup_ChanPattern18 = 0;
UNS8 FuncGroup_ChanPattern19 = 0;
UNS8 FuncGroup_ChanPattern20 = 0;
UNS8 FuncGroup_ChanPattern21 = 0;
UNS8 FuncGroup_ChanPattern22 = 0;
UNS8 FuncGroup_ChanPattern23 = 0;
UNS8 FuncGroup_ChanPattern24 = 0;
UNS8 FuncGroup_ChanPattern25 = 0;
UNS8 FuncGroup_ChanPattern26 = 0;
UNS8 FuncGroup_ChanPattern27 = 0;
UNS8 FuncGroup_ChanPattern28 = 0;
UNS8 FuncGroup_ChanPattern29 = 0;
UNS8 FuncGroup_ChanPattern30 = 0;
UNS8 FuncGroup_ChanPattern31 = 0;
UNS8 FuncGroup_ChanPattern32 = 0;
UNS8 FuncGroup_ChanPattern33 = 0;
UNS8 FuncGroup_ChanPattern34 = 0;
UNS8 FuncGroup_ChanPattern35 = 0;
UNS8 FuncGroup_ChanPattern36 = 0;
UNS8 FuncGroup_ChanPattern37 = 0;
UNS8 FuncGroup_ChanPattern38 = 0;
UNS8 FuncGroup_ChanPattern39 = 0;
UNS8 FuncGroup_ChanPattern40 = 0;
UNS8 FuncGroup_ChanPattern41 = 0;
UNS8 FuncGroup_ChanPattern42 = 0;
UNS8 FuncGroup_ChanPattern43 = 0;
UNS8 FuncGroup_ChanPattern44 = 0;
UNS8 FuncGroup_ChanPattern45 = 0;
UNS8 FuncGroup_ChanPattern46 = 0;
UNS8 FuncGroup_ChanPattern47 = 0;
UNS8 FuncGroup_ChanPattern48 = 0;
UNS8 Num_ChanPatterns = 0;        //0-48
UNS8 channel_PatternTransfer = 0;
UNS8 commandID_PatternTransfer = 0;
UNS8 numPoints_PatternTransfer = 0;
UNS8 xValues_PatternTransfer[PATTERN_ARRAYSIZE] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
UNS8 pwValues_PatternTransfer[PATTERN_ARRAYSIZE] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
UNS8 ampValues_PatternTransfer[PATTERN_ARRAYSIZE] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};

UNS8 StimTiming[4] = {20, 21, 22, 23};          //2800.1 time at which pulses are scheduled to occur (may get bumped if setup takes longer than time allotted)        
UNS8 SyncInterval[4] = {1, 1, 1, 1};            //2800.2 number of syncs before scheduler starts for each channel
UNS8 SyncPush = 0;                              //2800.3 sub-ms lining up between modules relative to SYNC, if greater than max setting, drift +/-1ms drift occurs between modules
                    //At 1 or 8 MHz, in units of 8us (max setting = 124).  
                    //At 4 MHz, in units of 16us (max setting = 62), At 2 MHz in units of 32us (max setting = 30)

UNS8 AutoSyncTime = 255;                        //2800.4  tick in scheduler when autosync will be generated
UNS8 MaxAutoSyncCount = 5;                      //2800.5  max consecutive auto syncs allowed (set to 255 for indefinite)
UNS8 DischargeTime = 5;                      //2800.6  minimum time required for discharge after pulse (<4 will be treated as 4)

UNS8 StimVOSsteps = 1;                        //3210.6  increments used for raising VOS from MinVOS to StimVOS (Setting >4 may offset stim timing, takes ~0.2ms per step. )
UNS8 MinVOSsteps = 50;                        //3210.7  increments used for raising VOS from off to MinVOS (Use > 20 to reduce VIN sag, when setting MinVOS=StimVOS.  Takes ~0.2ms per step. 
UNS8 SetupAnode = 0;                          //3210.8  Anode connection: 0 leaves anode connected to case all the time, 1 disconnects anode between groups of pulses.  
                                                        //Connected by default on startup until first pulse

UNS8 ActualStimTiming[4] = {0,0,0,0};          //2801.1 time at which actual pulses occurred for last stim pulses
UNS8 MaxActualStimTiming[4] = {0,0,0,0};       //2801.2 the highest tick time at which pulse events actually occurred
UNS8 AutoSyncCount = 0;                        //2801.3  number of consecutive autosyncs that have occured since last syncs
UNS16 TotalAutoSyncCount = 0;                  //2801.4 total auto syncs generated (results in held command but no loss in stimulation)
UNS16 MaxAutoSyncExceededCount = 0 ;           //2801.5 number of times MaxAutoSyncCount was exceeded (results in gap in stimulation)




UNS8 ActiveFunctionGroups[4] = {0,0,0,0};

UNS8 Channel_IPI = 50;

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict_bDeviceNodeId = 4;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDict_iam_a_slave = 1;

TIMER_HANDLE ObjDict_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict_obj1000 = 0x53504E4E;	/* 1397771854 */
                    const subindex ObjDict_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict_obj1001 = 0x0;	/* 0 */
                    const subindex ObjDict_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDict_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 ObjDict_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 ObjDict_obj1006 = 0xFF;	/* 0 */
                    const subindex ObjDict_Index1006[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1006 }
                     };
                   

/* index 0x1008 :   Manufacturer Device Name. */
                    INTEGER8 ObjDict_obj1008[24] = "4ch Pulse Generator PG-4";
                    const subindex ObjDict_Index1008[] = 
                     {
                       { RO, visible_string, 24, (void*)&ObjDict_obj1008 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDict_obj1014 = 0x80 + 0x02;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 ObjDict_highestSubIndex_obj1016 = 0;
                    UNS32 ObjDict_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 ObjDict_obj1017 = 2311;	/*  - 2.3 sec prime update*/
                    ODCallback_t ObjDict_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    const subindex ObjDict_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    INTEGER8 ObjDict_obj1018_Vendor_ID[10] = "NNPS";
                    UNS8 ObjDict_obj1018_Product_Code = 0x4;	
                    UNS32 ObjDict_obj1018_Revision_Number = APP_REV;	
                    UNS32 ObjDict_obj1018_Serial_Number = 0x0000;	/* 152592 */
                    const subindex ObjDict_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1018 },
                       { RO, visible_string, 10, (void*)&ObjDict_obj1018_Vendor_ID },
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x602;	/* 1538 */
                    UNS32 ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x582;	/* 1410 */
                    const subindex ObjDict_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1400_Source_Address = 0x0;	/* 387 */
                    UNS8 ObjDict_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 ObjDict_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1400_Event_Timer = 0x0;	/* 0 */
                    const subindex ObjDict_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1400_Source_Address },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1400_Event_Timer }
                     };


/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1600[] = 
                    {
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00	/* 0 */
                    };
                    subindex ObjDict_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[7] }
                     };


/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1800_COB_ID_used_by_PDO = 0x182;	/* use 0x80000182 to disable PDO */
                    UNS8 ObjDict_obj1800_Transmission_Type = 0xFD;	/* use 0xFD to disable */
                    UNS16 ObjDict_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1800_Event_Timer }
                     };



/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A00[] = 
                    {
                      0x00,     /* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00	/* 0 */
                    };
                    const subindex ObjDict_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[7] }
                     };


/* index 0x2000 :   Mapped variable Clock */
                    UNS8 ObjDict_highestSubIndex_obj2000 = 1; /* number of subindex - 1*/
                    ODCallback_t Clock_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index2000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2000 },
                       { RW, uint8, sizeof (UNS8), (void*)&clockRate }
                     };

/* index 0x2001 :   Mapped variable Control */
                    UNS8 ObjDict_highestSubIndex_obj2001 = 4; /* number of subindex - 1*/
                    const subindex ObjDict_Index2001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_ScriptStatus },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_CurrentGroup },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_profileWrite },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_profileSelect }
                     };

/* index 0x2002 :   Mapped variable X-Network */
                    UNS8 ObjDict_highestSubIndex_obj2002 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2002[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2002 },
                       { RW, uint8, 4, (void*)&X_Network[0] }
                     };

/* index 0x2003 :   Mapped variable Temperature */
                    UNS8 ObjDict_highestSubIndex_obj2003 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2003[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2003 },
                       { RO, uint16, sizeof (UNS16), (void*)&Temperature }
                     };



/* index 0x2010 :   Mapped variable Status */
                    UNS8 ObjDict_highestSubIndex_obj2010 = 9; /* number of subindex - 1*/
                    const subindex ObjDict_Index2010[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2010 },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_modeSelect },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_numTPDO },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_numRPDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_channelSelect },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_profileSelect },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_profileWrite },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_NodeId },
                       { RW, uint16, sizeof (UNS16), (void*)&Status_TestValue },
                       { RW, uint16, sizeof (UNS16), (void*)&Status_NodeTest }                  
                       
                     };

/* index 0x2011 :   Mapped variable Accelerometer Values */
                    UNS8 ObjDict_highestSubIndex_obj2011 = 3; /* number of subindex - 1*/
                    const subindex ObjDict_Index2011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2011 },
                       { RW, uint8, 4, (void*)&Accelerometers[0] },
                       { RW, uint8, 4, (void*) &AccelerometersFiltered[0] },
                       { RW, int8, 4, (void*) &AccelerometersTilt[0] }
                     };

/* index 0x2012 :   Mapped variable Accelerometer Settings */
                    UNS8 ObjDict_highestSubIndex_obj2012 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2012[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2012 },
                       { RW, uint8, sizeof (UNS8), (void*) &AccelerometerSettings }
                     };
                    
/* index 0x2020 :   Mapped variable RecordTransfer */
                    UNS8 ObjDict_highestSubIndex_obj2020 = 7;
                    const subindex ObjDict_Index2020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2020 },
                       { RW, uint32, sizeof (UNS32), (void*)&AddressRequest },    // 1
                       { RW, uint8, 36, (void*)&ReadMemoryData[0] },              // 19
                       { RW, uint32, sizeof (UNS32), (void*)&addressCounter },    // 21
                       { RW, uint8, sizeof (UNS8), (void*)&memorySelect },
                       { RW, uint8, sizeof (UNS8), (void*)&triggerReadMemory },
                       { RW, uint8, sizeof (UNS8), (void*)&writeByteMemory },
                       { RW, uint8, sizeof (UNS8), (void*)&statusByteMemory }
                      
                     };
                    
/* index 0x2500 :   Mapped variable CAN */
                    UNS8 ObjDict_highestSubIndex_obj2500 = 11; /* number of subindex - 1*/
                    const subindex ObjDict_Index2500[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2500 },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_TotalErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_BitErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_StuffErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_FormErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_OtherErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Rx_ErrCounter },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Tx_ErrCounter },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Receive_BEI },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Receive_Messages },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Transmit_Messages },
                       { RO, uint16, sizeof (UNS16),  (void*)&CAN_Interrupts_Off }
                     };
                    
/* index 0x2800 :   Mapped variable Scheduler settings*/
                    UNS8 ObjDict_highestSubIndex_obj2800 = 6; /* number of subindex - 1*/ 
                    const subindex ObjDict_Index2800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2800 },
                       { RW, uint8, 4*sizeof (UNS8), (void*)&StimTiming[0] },
                       { RW, uint8, 4*sizeof (UNS8), (void*)&SyncInterval[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&SyncPush },
                       { RW, uint8, sizeof (UNS8), (void*)&AutoSyncTime },
                       { RW, uint8, sizeof (UNS8), (void*)&MaxAutoSyncCount },
                       { RW, uint8, sizeof (UNS8), (void*)&DischargeTime }
                     };
                    
 /* index 0x2801 :   Mapped variable Scheduler monitor */                   
                    UNS8 ObjDict_highestSubIndex_obj2801 = 5; /* number of subindex - 1*/ 
                    const subindex ObjDict_Index2801[] = 
                    {
                      { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2801 }, 
                      { RO, uint8, 4*sizeof (UNS8), (void*)&ActualStimTiming[0] },
                      { RW, uint8, 4*sizeof (UNS8), (void*)&MaxActualStimTiming[0] },
                      { RO, uint8, sizeof (UNS8), (void*)&AutoSyncCount },
                      { RW, uint16, sizeof (UNS16), (void*)&TotalAutoSyncCount },
                      { RW, uint16, sizeof (UNS16), (void*)&MaxAutoSyncExceededCount }
                     };
                    
/* index 0x2900 :   Mapped variable RestoreList */
                    UNS8 ObjDict_highestSubIndex_obj2900 = 1; /* number of subindex - 1*/  
                    UNS16 RestoreList[9] = { 0x1400, /*RPDO Params(10)*/ \
                                              0x1600, /*RPDO Mapping(32)*/ \
                                              0x1800, /*TPDO Params(10)*/ \
                                              0x1A00, /*TPDO Mapping(32)*/ \
                                              0x2001, /*Control(4)*/\
                                              0x2012, /*Accelerometer Settings*/\
                                              0x2800, /*SYNC Timing(8)*/\
                                              0x3210, /*ChanConfig(22)*/ \
                                              0x3300  /*FuncGroups(49)*/}; 
                     
                    const subindex ObjDict_Index2900[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2900 },
                       { RO, uint16, 8*2, (void*)&RestoreList[0] }
                     };

/* index 0x3000 :   Mapped variable Diagnostics */
                    UNS8 ObjDict_highestSubIndex_obj3000 = 5; /* number of subindex - 1*/
                    const subindex ObjDict_Index3000[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3000 },
                       { RW, uint8, sizeof (UNS8), (void*)&DiagnosticsEnabled },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VIN },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VIC },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VOS },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_3V3 }
                     };
                    
/* index 0x3200 :   Mapped variable CommandValues */
                    UNS8 ObjDict_highestSubIndex_obj3200 = 2; /* number of subindex - 1*/  
                    const subindex ObjDict_Index3200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3200 },
                       { RW, uint8, 8*sizeof (UNS8), (void*)&CommandValues[0] },
                       { RO, uint8, 4*sizeof (UNS8), (void*)&ActiveFunctionGroups[0] }
                     };
                    

/* index 0x3210 :   Mapped variable Channel_Config */
                    UNS8 ObjDict_highestSubIndex_obj3210 = 9; /* number of subindex - 1*/
                    const subindex ObjDict_Index3210[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3210 },
                       { RW, uint8, 8, (void*)&Channel_Config_AmpMax[0] },
                       { RW, uint16, 4*2, (void*)&Channel_Config_Period[0] },
                       { RW, uint16, sizeof (UNS16), (void*)&Channel_StimVOS},
                       { RW, uint16, sizeof (UNS16), (void*)&Channel_MinVOS},
                       { RW, uint8, 4, (void*)&Channel_InRegulation[0] },
                       { RW, uint8, sizeof (UNS8), (void*)&StimVOSsteps },
                       { RW, uint8, sizeof (UNS8), (void*)&MinVOSsteps },
                       { RW, uint8, sizeof (UNS8), (void*)&SetupAnode },
                       { RW, uint8, sizeof (UNS8), (void*)&Channel_IPI }
                     };

/* index 0x3211 :   Mapped variable X_ChannelMap */
                    UNS8 ObjDict_highestSubIndex_obj3211 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index3211[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3211 },
                       { RW, uint8, 4, (void*)&X_ChannelMap }
                     };

/* index 0x3212 :   Mapped variable Y-Current Values by channel */
                    
                    UNS8 ObjDict_highestSubIndex_obj3212 = 4; /* number of subindex - 1*/
                    const subindex ObjDict_Index3212[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3212 },
                       { RW, uint8, 2, (void*)&Chan1_SetValues[0] },
                       { RW, uint8, 2, (void*)&Chan2_SetValues[0] },
                       { RW, uint8, 2, (void*)&Chan3_SetValues[0] },
                       { RW, uint8, 2, (void*)&Chan4_SetValues[0] },
                                    
                     };

                    //remove?
/* index 0x3213 :   Mapped variable Y-Current */
                    UNS8 ObjDict_highestSubIndex_obj3213 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index3213[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3213 },
                       { RW, uint8, 8, (void*)&Y_Current[0] }
                     };

/* index 0x3300 :   Mapped variable FuncGroup_ChanPattern */
                    UNS8 ObjDict_highestSubIndex_obj3300 = 49; /* number of subindex - 1*/
                    const subindex ObjDict_Index3300[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3300 },
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern01},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern02},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern03},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern04},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern05},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern06},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern07},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern08},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern09},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern10},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern11},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern12},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern13},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern14},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern15},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern16},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern17},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern18},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern19},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern20},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern21},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern22},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern23},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern24},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern25},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern26},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern27},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern28},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern29},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern30},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern31},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern32},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern33},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern34},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern35},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern36},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern37},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern38},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern39},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern40},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern41},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern42},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern43},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern44},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern45},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern46},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern47},
                       { RW, uint8, sizeof (UNS8), (void*)&FuncGroup_ChanPattern48},
                       { RW, uint8, sizeof (UNS8), (void*)&Num_ChanPatterns}
                     };

/* index 0x3300 :  Pattern Transfer */
                    UNS8 ObjDict_highestSubIndex_obj3301 = 6; /* number of subindex - 1*/
                    const subindex ObjDict_Index3301[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3301 },
                       { RW, uint8, sizeof (UNS8), (void*)&channel_PatternTransfer },
                       { RW, uint8, sizeof (UNS8), (void*)&commandID_PatternTransfer },
                       { RW, uint8, sizeof (UNS8), (void*)&numPoints_PatternTransfer },
                       { RW, uint8, PATTERN_ARRAYSIZE, (void*)&xValues_PatternTransfer[0] },
                       { RW, uint8, PATTERN_ARRAYSIZE, (void*)&pwValues_PatternTransfer[0] },
                       { RW, uint8, PATTERN_ARRAYSIZE, (void*)&ampValues_PatternTransfer[0] }
                     };
                 
/**************************************************************************/
/* Declaration of variables                                       */
/**************************************************************************/

const indextable ObjDict_objdict[] = 
{
  { (subindex*)ObjDict_Index1000,sizeof(ObjDict_Index1000)/sizeof(ObjDict_Index1000[0]), 0x1000},
  { (subindex*)ObjDict_Index1001,sizeof(ObjDict_Index1001)/sizeof(ObjDict_Index1001[0]), 0x1001},
  { (subindex*)ObjDict_Index1006,sizeof(ObjDict_Index1006)/sizeof(ObjDict_Index1006[0]), 0x1006},
  { (subindex*)ObjDict_Index1008,sizeof(ObjDict_Index1008)/sizeof(ObjDict_Index1008[0]), 0x1008},
  { (subindex*)ObjDict_Index1017,sizeof(ObjDict_Index1017)/sizeof(ObjDict_Index1017[0]), 0x1017},
  { (subindex*)ObjDict_Index1018,sizeof(ObjDict_Index1018)/sizeof(ObjDict_Index1018[0]), 0x1018},
  { (subindex*)ObjDict_Index1200,sizeof(ObjDict_Index1200)/sizeof(ObjDict_Index1200[0]), 0x1200},
  { (subindex*)ObjDict_Index1400,sizeof(ObjDict_Index1400)/sizeof(ObjDict_Index1400[0]), 0x1400},  
  { (subindex*)ObjDict_Index1600,sizeof(ObjDict_Index1600)/sizeof(ObjDict_Index1600[0]), 0x1600}, 
  { (subindex*)ObjDict_Index1800,sizeof(ObjDict_Index1800)/sizeof(ObjDict_Index1800[0]), 0x1800},
  { (subindex*)ObjDict_Index1A00,sizeof(ObjDict_Index1A00)/sizeof(ObjDict_Index1A00[0]), 0x1A00},
  { (subindex*)ObjDict_Index2000,sizeof(ObjDict_Index2000)/sizeof(ObjDict_Index2000[0]), 0x2000},
  { (subindex*)ObjDict_Index2001,sizeof(ObjDict_Index2001)/sizeof(ObjDict_Index2001[0]), 0x2001},
  { (subindex*)ObjDict_Index2002,sizeof(ObjDict_Index2002)/sizeof(ObjDict_Index2002[0]), 0x2002},
  { (subindex*)ObjDict_Index2003,sizeof(ObjDict_Index2003)/sizeof(ObjDict_Index2003[0]), 0x2003},
  { (subindex*)ObjDict_Index2010,sizeof(ObjDict_Index2010)/sizeof(ObjDict_Index2010[0]), 0x2010},
  { (subindex*)ObjDict_Index2011,sizeof(ObjDict_Index2011)/sizeof(ObjDict_Index2011[0]), 0x2011},
  { (subindex*)ObjDict_Index2012,sizeof(ObjDict_Index2012)/sizeof(ObjDict_Index2012[0]), 0x2012},
  { (subindex*)ObjDict_Index2020,sizeof(ObjDict_Index2020)/sizeof(ObjDict_Index2020[0]), 0x2020},
  { (subindex*)ObjDict_Index2500,sizeof(ObjDict_Index2500)/sizeof(ObjDict_Index2500[0]), 0x2500},
  { (subindex*)ObjDict_Index2800,sizeof(ObjDict_Index2800)/sizeof(ObjDict_Index2800[0]), 0x2800},
  { (subindex*)ObjDict_Index2801,sizeof(ObjDict_Index2801)/sizeof(ObjDict_Index2801[0]), 0x2801},
  { (subindex*)ObjDict_Index2900,sizeof(ObjDict_Index2900)/sizeof(ObjDict_Index2900[0]), 0x2900},
  { (subindex*)ObjDict_Index3000,sizeof(ObjDict_Index3000)/sizeof(ObjDict_Index3000[0]), 0x3000},
  { (subindex*)ObjDict_Index3200,sizeof(ObjDict_Index3200)/sizeof(ObjDict_Index3200[0]), 0x3200},
  { (subindex*)ObjDict_Index3210,sizeof(ObjDict_Index3210)/sizeof(ObjDict_Index3210[0]), 0x3210},
  { (subindex*)ObjDict_Index3211,sizeof(ObjDict_Index3211)/sizeof(ObjDict_Index3211[0]), 0x3211},
  { (subindex*)ObjDict_Index3212,sizeof(ObjDict_Index3212)/sizeof(ObjDict_Index3212[0]), 0x3212},
  { (subindex*)ObjDict_Index3213,sizeof(ObjDict_Index3213)/sizeof(ObjDict_Index3213[0]), 0x3213},
  { (subindex*)ObjDict_Index3300,sizeof(ObjDict_Index3300)/sizeof(ObjDict_Index3300[0]), 0x3300},
  { (subindex*)ObjDict_Index3301,sizeof(ObjDict_Index3301)/sizeof(ObjDict_Index3301[0]), 0x3301}
};

const indextable * ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
                case 0x1006: i = 2;break;
		case 0x1008: i = 3;break;
		case 0x1017: i = 4;*callbacks = ObjDict_Index1017_callbacks; break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1400: i = 7;break;	
		case 0x1600: i = 8;break;	
		case 0x1800: i = 9;*callbacks = ObjDict_Index1800_callbacks; break;	
		case 0x1A00: i = 10;break;
		case 0x2000: i = 11;break;
		case 0x2001: i = 12;break;
		case 0x2002: i = 13;break;
		case 0x2003: i = 14;break;
		case 0x2010: i = 15;break;
		case 0x2011: i = 16;break;
                case 0x2012: i = 17;break;
                case 0x2020: i = 18;break;
                case 0x2500: i = 19;break;
                case 0x2800: i = 20;break;
                case 0x2801: i = 21;break;
                case 0x2900: i = 22;break;
                case 0x3000: i = 23;break;
                case 0x3200: i = 24;break;
		case 0x3210: i = 25;break;
		case 0x3211: i = 26;break;
		case 0x3212: i = 27;break;
		case 0x3213: i = 28;break;
		case 0x3300: i = 29;break;
                case 0x3301: i = 30;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDict_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
//Should match number of TPDOs!
s_PDO_status ObjDict_PDO_status[1] = {s_PDO_status_Initializer};
//s_PDO_status ObjDict_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index ObjDict_firstIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  9, /* PDO_TRS */
  10 /* PDO_TRS_MAP */
};

const quick_index ObjDict_lastIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  9, /* PDO_TRS */
  10 /* PDO_TRS_MAP */
};

const UNS16 ObjDict_ObjdictSize = sizeof(ObjDict_objdict)/sizeof(ObjDict_objdict[0]); 

CO_Data ObjDict_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict);

